#!/bin/bash
branch="$1"
arch=$(dpkg --print-architecture)

case "${branch}" in
	"xenial"*) repo="repo.ubports.com";;
	*) repo="repo2.ubports.com";;
esac

while read pkg
do
	status=$(apt-cache policy $pkg|awk '/Installed/{print $2}')
	if [[ -n "${status}" && "$status" != "(none)" ]]; then
		echo -n "${pkg} "
	fi
done < <(awk '/Package/{print $2}' /var/lib/apt/lists/${repo}_dists_${branch//_/%5f}_main_binary-${arch}_Packages|uniq)
