#!/bin/bash
branch=$1
arch=$(dpkg --print-architecture)

case "${branch}" in
	"xenial"*) repo="repo.ubports.com";;
	*) repo="repo2.ubports.com";;
esac

readarray -t pkgs < <(awk '/Package/{print $2}' /var/lib/apt/lists/${repo}_dists_${branch//_/%5f}_main_binary-${arch}_Packages|uniq)
relpkgs=()
for pkg in "${pkgs[@]}"
do
	status=$(apt-cache policy $pkg|awk '/Installed/{print $2}')
	[ "$status" != "(none)" ] && relpkgs=${relpkgs}" "${pkg}
done
apt-get install $relpkgs
