#!/bin/bash
while read list
do
	list=$(basename "${list}")
	if [[ "${list}" != "ubports.list" && "${list}" != "ubports-android9.list" ]]; then
		list="${list/ubports-/}"
		pkgs=$(pkgcheck "${list/.list/}")" "${pkgs}
	 fi
done < <(ls /etc/apt/sources.list.d/*)
apt-get install ${pkgs}
